### PR TITLE
fix(travis): fixes for Archlinux and CentOS

### LINKED ISSUE #33: [BUG] Travis: jobs fail until reboot (arch)
### Pillar / config used

---

### Describe the bug

A full run of `iscsi` state modifies kernel and issues arise:
```
       Summary for local
       -------------
       Succeeded: 68 (changed=49)
       Failed:    11
       -------------
       Total states run:     79
       Total run time:   93.135 s
```

### Expected behaviour

```
cloning iscsi-formula from saltstack-formulas ...

local:
    ----------
    base:
        - users
        - iscsi
run salt: this takes a while, please be patient ...
-------------
Succeeded: 52 (changed=15)
Failed:     0
-------------
```

### LINKED ISSUE #34: [BUG] make python-configshell-fb fails (Archlinux)
### Versions reports (master & minion)

https://aur.archlinux.org/packages/python2-configshell-fb

### Pillar / config used

---

### Describe the bug

```
$ git clone https://aur.archlinux.org/packages/python-configshell-fb
$ cd python-configshell-fb
$ makepkg -si --noconfirm -f
==> Making package: python-configshell-fb 1.1.26-1 (Sun 19 Apr 2020 08:46:35 PM UTC)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading v1.1.26.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   134  100   134    0     0    210      0 --:--:-- --:--:-- --:--:--   210
100 34774    0 34774    0     0  18837      0 --:--:--  0:00:01 --:--:-- 30992
==> Validating source files with sha512sums...
    v1.1.26.tar.gz ... Passed
==> Extracting sources...
  -> Extracting v1.1.26.tar.gz with bsdtar
==> Entering fakeroot environment...
==> Starting package_python-configshell-fb()...
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/configshell
< CUT >
==> Installing python-configshell-fb package group with pacman -U...
loading packages...
resolving dependencies...
warning: cannot resolve "python2-urwid", a dependency of "python2-configshell-fb"
:: The following package cannot be upgraded due to unresolvable dependencies:
      python2-configshell-fb

:: Do you want to skip the above package for this upgrade? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: unable to satisfy dependency 'python2-urwid' required by python2-configshell-fb
==> WARNING: Failed to install built package(s).
```

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [x] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

* Fixes #34

### Describe the changes you're proposing

Travis CI tests are failing for CentOS and Archlinux.
- CentOS cannot start `target` service as kernel boot is pending.
- Archlinux states had some weakness (fixed) and the `python-configshell-fb` package is broken.

#33 and #34 

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
This PR has a workaround for https://bugs.archlinux.org/task/66317

**Comment by myii** [comment]
@noelmcloughlin I went into a long description of the issue with Arch Linux on the `master` branch in the #testing channel on Slack.  You can see it here before it disappears in Slack's history:

* https://saltstackcommunity.slack.com/archives/C7KKN9P6W/p1588245779041300

Long story short, `py2` support has been removed from Sodium, which is what our current `master` branch is leading to.  So until we figure out how to get the `salt-bootstrap` to install on Arch `py3`, this specific Docker image is useless (i.e. `netmanagers/salt-master-py2:arch-base-latest`).  However, both `3000.2` and `2019.2` still work, so please use those instead.

**Comment by noelmcloughlin** [comment]
Okay, I was unaware of that. I will use 2019.2 image - Travis passes now

**Comment by myii** [comment]
@noelmcloughlin Due to conflicts, I rebased this PR on top of master and force pushed.  You'll see that your actual commits are virtually identical except I removed one occurrence of `arch-base-latest-master-py2` in `kitchen.yml` from the first commit.  Waiting for the tests to complete now.

**Comment by myii** [comment]
@noelmcloughlin I've also modified the main body of the original post so that #33 and #34 are closed automatically.  Please adjust that if it isn't correct.

**Comment by myii** [comment]
@noelmcloughlin Well, Travis is failing again.  It looks like a temperamental situation.  Please adjust your settings so that you can pull the changes from here before continuing with this.  Or if that's too much, perhaps you want to go ahead and merge this and then start a new PR to fix these.

**Comment by noelmcloughlin** [comment]
I would like to merge this if you are okay with that? Again thanks for your review.

I could take a fresh look at CI some other time.

**Pull request merged**
