### PR TITLE
iSNS and iSCSI for GNU/Linux and FreeBSD

### PR DESCRIPTION
**Pull request by noelmcloughlin**
The original formula supports FreeBSD only.   This PR extends support to iSNS/iSCSI implementations across various Linux. I think the code is good enough to merge - its heavily tested.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Verified on Centos7
```
----------
          ID: iscsi_isns_install_yum-plugin-versionlock_pkg
    Function: pkg.installed
        Name: yum-plugin-versionlock
      Result: True
     Comment: 1 targeted package was installed/updated.
              Package yum-plugin-versionlock is not being held.
     Started: 19:15:11.122254
    Duration: 11589.437 ms
     Changes:   
              ----------
              yum-plugin-versionlock:
                  ----------
                  new:
                      1.1.31-45.el7
                  old:
----------
          ID: iscsi_isns_install_isns-utils_pkg
    Function: pkg.installed
        Name: isns-utils
      Result: True
     Comment: All specified packages are already installed.
              Package isns-utils is not being held.
     Started: 19:15:22.731720
    Duration: 854.614 ms
     Changes:   
----------
          ID: iscsi_isns_service_config
    Function: file.managed
        Name: /etc/isns/isnsd.conf
      Result: True
     Comment: File /etc/isns/isnsd.conf updated
     Started: 19:15:23.589998
    Duration: 96.541 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,129 +1,20 @@
                  -#
                  -# Sample iSNS Server configuration file
                  -#
                  +##################################################################
                  +# Managed by salt. Changes risk being overwritten. READ isnsd(10)!
                  +##################################################################
                   
                  -# The source name. This is an iSCSI qualified name,
                  -# and identifies the client uniquely.
                  -#
                  -# If left empty, the source name is derived from
                  -# the client's hostname.
                  -#
                  -#SourceName	= iqn.2006-01.com.example.host1
                   
                  -# Where to store the database.
                  -# If you leave this empty, isnsd will keep its
                  -# database in memory.
                  -# Setting this to an absolute path name will
                  -# make isnsd keep its database in a directory
                  -# hierarchy below that directory.
                  -Database	= /var/lib/isns
                   
                  -# The iSNS server can purge registered entities
                  -# after a certain period of inactivity. This is
                  -# called the registration period.
                  -# Clients who register objects are supposed to
                  -# refresh their registration within this period.
                  -#
                  -# The default value is 0, which disables this
                  -# feature.
                  -RegistrationPeriod	= 10m
                   
                  -# iSNS scopes visibility of other nodes using so-called
                  -# Discovery Domains. A storage node A will only "see"
                  -# storage node B, if both are members of the same
                  -# discovery domain.
                  -#
                  -# So if a storage node is registered which is not part of
                  -# any discovery domain, it will not see any other nodes.
                  -#
                  -# By setting DefaultDiscoveryDomain=1, you can tell isnsd to
                  -# create a virtual "default discovery domain", which 
                  -# holds all nodes that are not part of any administratively
                  -# configured discovery domain.
                  -DefaultDiscoveryDomain	= 1
                   
                  -# Make the iSNS server register itself with SLP.
                  -# Clients will be able to discover the server by
                  -# querying for service type "iscsi:sms", and a query
                  -# of "(protocols=isns)"
                  -SLPRegister		= 1
                  -
                  -# Authentication enable/disable.
                  -# When set to 1, the client will sign
                  -# all messages, and expect all server messages
                  -# to be signed.
                  -#
                  -# Authentication requires a valid private DSA
                  -# key in AuthKeyFile, and the server's DSA public
                  -# key in ServerKeyFile.
                  -#
                  -# The default is to use authentication if the
                  -# requires keys are installed, and use unauthenticated
                  -# iSNS otherwise.
                  -#Security	= 1
                  -
                  -# Location of the client's private key.
                  -# The file must contain a PEM encoded DSA key.
                  -# The default is /etc/isns/auth_key
                  -#AuthKeyFile	= /etc/isns/auth_key
                  -
                  -# Location of the servers's public key.
                  -# The file must contain a PEM encoded DSA key.
                  -# The default is /etc/isns/server_key.pub
                  -#ServerKeyFile	= /etc/isns/server_key.pub
                  -
                  -# This describes where the iSNS server stores
                  -# authentication keys and policy information.
                  -# Two options are currently supported: a
                  -# simple key store (flat directory with public
                  -# keys in PEM encoded files), and the iSNS
                  -# database itself
                  -#ClientKeyStore	= /etc/isns/keystores
                  -ClientKeyStore	= DB:
                  -
                  -# When transmitting State Change Notification,
                  -# we expect the client to ack them. If the
                  -# ACK doesn't arrive in due time, we retransmit
                  -# for a limited number of attempts, cycling
                  -# through the available portals.
                  -SCNTimeout	= 60
                  -SCNRetries	= 3
                  -
                  -# Configuration of ESI.
                  -# Defaults are
                  -#  ESIMaxInterval = 1h
                  -#  ESIMinInterval = 60s
                  -#  ESIRetries     = 3
                  -# Setting ESIRetries to 0 disables ESI support, and makes
                  -# the server reject any portal registrations that specify
                  -# an ESI portal.
                  -ESIMinInterval	= 1m
                  -ESIMaxInterval	= 2m
                  -ESIRetries	= 3
                  -
                  -# In order to prevent replay attacks, the
                  -# authentication blocks carried by iSNS
                  -# include a time stamp. The following two
                  -# parameters control how we verify the
                  -# time stamp
                  -Auth.ReplayWindow = 2m
                  -Auth.TimeStampJitter = 1s
                  -
                  -# Maximum number of incoming connections
                  -# accepted.
                  -# Network.MaxSockets = 1024
                  -
                  -# Time to wait for a TCP connection to be
                  -# established.
                  -# (Client only)
                  -# Network.ConnectTimeout = 60
                  -
                  -# When a connection attempt failed, we wait
                  -# before we try connecting again.
                  -# (Client only)
                  -# Network.ReonnectTimeout = 10
                  -
                  -# Total amount of time to wait before timing
                  -# out a call to the iSNS server.
                  -# (Client only)
                  -# Network.CallTimeout = 60
                  +  Auth.ReplayWindow=2m
                  +  Auth.TimeStampJitter=1s
                  +  ClientKeyStore=DB:
                  +  Database=/var/lib/isns
                  +  DefaultDiscoveryDomain=1
                  +  ESIMaxInterval=2m
                  +  ESIMinInterval=1m
                  +  ESIRetries=3
                  +  RegistrationPeriod=10m
                  +  SCNRetries=3
                  +  SCNTimeout=60
                  +  SLPRegister=1
              mode:
                  0640
----------
          ID: iscsi_isns_service
    Function: service.running
        Name: isns
      Result: False
     Comment: Running scope as unit run-8752.scope.
              Failed to start isns.service: Unit not found.
     Started: 19:15:23.699595
    Duration: 72.993 ms
     Changes:   
----------
          ID: iscsi_target_install_scsi-target-utils_pkg
    Function: pkg.installed
        Name: scsi-target-utils
      Result: True
     Comment: All specified packages are already installed.
              Package scsi-target-utils is not being held.
     Started: 19:15:23.772853
    Duration: 162.191 ms
     Changes:   
----------
          ID: iscsi_target_service_config
    Function: file.managed
        Name: /etc/tgt/conf.d/targets.conf
      Result: False
     Comment: Unable to manage file: Jinja error: 'unicode' object has no attribute 'items'
              /var/cache/salt/minion/files/base/iscsi/files/macros.jinja(2):
              ---
              {%- macro makeoutput(outdict, spaces=0, mapdiv='', kvdiv='', end='', quote='', comma='') -%}
              {%- for key, value in outdict|dictsort -%}    <======================
              {{ output(key, value, spaces, mapdiv, kvdiv, end, quote, comma,) }}
              {%- endfor -%}
              {%- endmacro -%}
              
              {%- macro output(key, value, spaces, mapdiv, kvdiv, end, quote, comma) -%}
              [...]
              ---
              Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 389, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "<template>", line 20, in top-level template code
                File "/var/cache/salt/minion/files/base/iscsi/files/macros.jinja", line 2, in template
                  {%- for key, value in outdict|dictsort -%}
                File "/usr/lib/python2.7/site-packages/jinja2/filters.py", line 223, in do_dictsort
                  return sorted(value.items(), key=sort_func)
              AttributeError: 'unicode' object has no attribute 'items'
     Started: 19:15:23.935987
    Duration: 94.377 ms
     Changes:   
----------
          ID: iscsi_target_service
    Function: file.line
        Name: /etc/rc.conf
      Result: True
     Comment: onlyif condition is false
     Started: 19:15:24.030544
    Duration: 426.468 ms
     Changes:   
----------
          ID: iscsi_target_service
    Function: service.running
        Name: target
      Result: False
     Comment: One or more requisite failed: iscsi.target.install.iscsi_target_service_config
     Started: 19:15:24.457794
    Duration: 0.012 ms
     Changes:   
----------
          ID: iscsi_initiator_remove_udisks2-doc_pkg
    Function: pkg.purged
        Name: udisks2-doc
      Result: True
     Comment: All specified packages are already absent
     Started: 19:15:24.457873
    Duration: 53.399 ms
     Changes:   
----------
          ID: iscsi_initiator_remove_libiscsi-devel_pkg
    Function: pkg.purged
        Name: libiscsi-devel
      Result: True
     Comment: All specified packages are already absent
     Started: 19:15:24.511476
    Duration: 5.452 ms
     Changes:   
----------
          ID: iscsi_initiator_remove_libvirt-daemon-driver-storage-scsi_pkg
    Function: pkg.purged
        Name: libvirt-daemon-driver-storage-scsi
      Result: True
     Comment: All specified packages are already absent
     Started: 19:15:24.517070
    Duration: 4.846 ms
     Changes:   
----------
          ID: iscsi_initiator_remove_libvirt-daemon-driver-storage-iscsi_pkg
    Function: pkg.purged
        Name: libvirt-daemon-driver-storage-iscsi
      Result: True
     Comment: All specified packages are already absent
     Started: 19:15:24.522049
    Duration: 4.732 ms
     Changes:   
----------
          ID: iscsi_initiator_install_libiscsi-utils_pkg
    Function: pkg.installed
        Name: libiscsi-utils
      Result: True
     Comment: All specified packages are already installed.
              Package libiscsi-utils is not being held.
     Started: 19:15:24.526918
    Duration: 153.669 ms
     Changes:   
----------
          ID: iscsi_initiator_install_udisks2-iscsi_pkg
    Function: pkg.installed
        Name: udisks2-iscsi
      Result: True
     Comment: All specified packages are already installed.
              Package udisks2-iscsi is not being held.
     Started: 19:15:24.680899
    Duration: 158.38 ms
     Changes:   
----------
          ID: iscsi_initiator_install_iscsi-initiator-utils_pkg
    Function: pkg.installed
        Name: iscsi-initiator-utils
      Result: True
     Comment: All specified packages are already installed.
              Package iscsi-initiator-utils is not being held.
     Started: 19:15:24.839593
    Duration: 158.54 ms
     Changes:   
----------
          ID: iscsi_initiator_service_config
    Function: file.managed
        Name: /etc/iscsi/iscsid.conf
      Result: True
     Comment: File /etc/iscsi/iscsid.conf updated
     Started: 19:15:25.000910
    Duration: 85.609 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,315 +1,28 @@
                  -#
                  -# Open-iSCSI default configuration.
                  -# Could be located at /etc/iscsi/iscsid.conf or ~/.iscsid.conf
                  -#
                  -# Note: To set any of these values for a specific node/session run
                  -# the iscsiadm --mode node --op command for the value. See the README
                  -# and man page for iscsiadm for details on the --op command.
                  -#
                  -
                  -######################
                  -# iscsid daemon config
                  -######################
                  -# If you want iscsid to start the first time an iscsi tool
                  -# needs to access it, instead of starting it when the init
                  -# scripts run, set the iscsid startup command here. This
                  -# should normally only need to be done by distro package
                  -# maintainers.
                  -#
                  -# Default for Fedora and RHEL. (uncomment to activate).
                  -# Use socket activation, but try to make sure the socket units are listening
                  -iscsid.startup = /bin/systemctl start iscsid.socket iscsiuio.socket
                  -# 
                  -# Default for upstream open-iscsi scripts (uncomment to activate).
                  -# iscsid.startup = /sbin/iscsid
                  -
                  -# Check for active mounts on devices reachable through a session
                  -# and refuse to logout if there are any.  Defaults to "No".
                  -# iscsid.safe_logout = Yes
                  -
                  -#############################
                  -# NIC/HBA and driver settings
                  -#############################
                  -# open-iscsi can create a session and bind it to a NIC/HBA.
                  -# To set this up see the example iface config file.
                  -
                  -#*****************
                  -# Startup settings
                  -#*****************
                  -
                  -# To request that the iscsi initd scripts startup a session set to "automatic".
                  -# node.startup = automatic
                  -#
                  -# To manually startup the session set to "manual". The default is automatic.
                  -node.startup = automatic
                  -
                  -# For "automatic" startup nodes, setting this to "Yes" will try logins on each
                  -# available iface until one succeeds, and then stop.  The default "No" will try
                  -# logins on all available ifaces simultaneously.
                  -node.leading_login = No
                  -
                  -# *************
                  -# CHAP Settings
                  -# *************
                  -
                  -# To enable CHAP authentication set node.session.auth.authmethod
                  -# to CHAP. The default is None.
                  -#node.session.auth.authmethod = CHAP
                  -
                  -# To set a CHAP username and password for initiator
                  -# authentication by the target(s), uncomment the following lines:
                  -#node.session.auth.username = username
                  -#node.session.auth.password = password
                  -
                  -# To set a CHAP username and password for target(s)
                  -# authentication by the initiator, uncomment the following lines:
                  -#node.session.auth.username_in = username_in
                  -#node.session.auth.password_in = password_in
                  -
                  -# To enable CHAP authentication for a discovery session to the target
                  -# set discovery.sendtargets.auth.authmethod to CHAP. The default is None.
                  -#discovery.sendtargets.auth.authmethod = CHAP
                  -
                  -# To set a discovery session CHAP username and password for the initiator
                  -# authentication by the target(s), uncomment the following lines:
                  -#discovery.sendtargets.auth.username = username
                  -#discovery.sendtargets.auth.password = password
                  -
                  -# To set a discovery session CHAP username and password for target(s)
                  -# authentication by the initiator, uncomment the following lines:
                  -#discovery.sendtargets.auth.username_in = username_in
                  -#discovery.sendtargets.auth.password_in = password_in
                  -
                  -# ********
                  -# Timeouts
                  -# ********
                  -#
                  -# See the iSCSI README's Advanced Configuration section for tips
                  -# on setting timeouts when using multipath or doing root over iSCSI.
                  -#
                  -# To specify the length of time to wait for session re-establishment
                  -# before failing SCSI commands back to the application when running
                  -# the Linux SCSI Layer error handler, edit the line.
                  -# The value is in seconds and the default is 120 seconds.
                  -# Special values:
                  -# - If the value is 0, IO will be failed immediately.
                  -# - If the value is less than 0, IO will remain queued until the session
                  -# is logged back in, or until the user runs the logout command.
                  -node.session.timeo.replacement_timeout = 120
                  -
                  -# To specify the time to wait for login to complete, edit the line.
                  -# The value is in seconds and the default is 15 seconds.
                  -node.conn[0].timeo.login_timeout = 15
                  -
                  -# To specify the time to wait for logout to complete, edit the line.
                  -# The value is in seconds and the default is 15 seconds.
                  -node.conn[0].timeo.logout_timeout = 15
                  -
                  -# Time interval to wait for on connection before sending a ping.
                  -node.conn[0].timeo.noop_out_interval = 5
                  -
                  -# To specify the time to wait for a Nop-out response before failing
                  -# the connection, edit this line. Failing the connection will
                  -# cause IO to be failed back to the SCSI layer. If using dm-multipath
                  -# this will cause the IO to be failed to the multipath layer.
                  -node.conn[0].timeo.noop_out_timeout = 5
                  -
                  -# To specify the time to wait for abort response before
                  -# failing the operation and trying a logical unit reset edit the line.
                  -# The value is in seconds and the default is 15 seconds.
                  -node.session.err_timeo.abort_timeout = 15
                  -
                  -# To specify the time to wait for a logical unit response
                  -# before failing the operation and trying session re-establishment
                  -# edit the line.
                  -# The value is in seconds and the default is 30 seconds.
                  -node.session.err_timeo.lu_reset_timeout = 30
                  -
                  -# To specify the time to wait for a target response
                  -# before failing the operation and trying session re-establishment
                  -# edit the line.
                  -# The value is in seconds and the default is 30 seconds.
                  -node.session.err_timeo.tgt_reset_timeout = 30
                  +#######################################################################
                  +# File managed by Salt. Changes risk being overwritten.
                  +# Implements format described in iscsid.conf(5)
                  +#######################################################################
                   
                   
                  -#******
                  -# Retry
                  -#******
                   
                  -# To specify the number of times iscsid should retry a login
                  -# if the login attempt fails due to the node.conn[0].timeo.login_timeout
                  -# expiring modify the following line. Note that if the login fails
                  -# quickly (before node.conn[0].timeo.login_timeout fires) because the network
                  -# layer or the target returns an error, iscsid may retry the login more than
                  -# node.session.initial_login_retry_max times.
                  -#
                  -# This retry count along with node.conn[0].timeo.login_timeout
                  -# determines the maximum amount of time iscsid will try to
                  -# establish the initial login. node.session.initial_login_retry_max is
                  -# multiplied by the node.conn[0].timeo.login_timeout to determine the
                  -# maximum amount.
                  -#
                  -# The default node.session.initial_login_retry_max is 8 and
                  -# node.conn[0].timeo.login_timeout is 15 so we have:
                  -#
                  -# node.conn[0].timeo.login_timeout * node.session.initial_login_retry_max =
                  -#								120 seconds
                  -#
                  -# Valid values are any integer value. This only
                  -# affects the initial login. Setting it to a high value can slow
                  -# down the iscsi service startup. Setting it to a low value can
                  -# cause a session to not get logged into, if there are distuptions
                  -# during startup or if the network is not ready at that time.
                  -node.session.initial_login_retry_max = 8
                  -
                  -################################
                  -# session and device queue depth
                  -################################
                  -
                  -# To control how many commands the session will queue set
                  -# node.session.cmds_max to an integer between 2 and 2048 that is also
                  -# a power of 2. The default is 128.
                  -node.session.cmds_max = 128
                  -
                  -# To control the device's queue depth set node.session.queue_depth
                  -# to a value between 1 and 1024. The default is 32.
                  -node.session.queue_depth = 32
                  -
                  -##################################
                  -# MISC SYSTEM PERFORMANCE SETTINGS
                  -##################################
                  -
                  -# For software iscsi (iscsi_tcp) and iser (ib_iser) each session
                  -# has a thread used to transmit or queue data to the hardware. For
                  -# cxgb3i you will get a thread per host.
                  -#
                  -# Setting the thread's priority to a lower value can lead to higher throughput
                  -# and lower latencies. The lowest value is -20. Setting the priority to
                  -# a higher value, can lead to reduced IO performance, but if you are seeing
                  -# the iscsi or scsi threads dominate the use of the CPU then you may want
                  -# to set this value higher.
                  -#
                  -# Note: For cxgb3i you must set all sessions to the same value, or the
                  -# behavior is not defined.
                  -#
                  -# The default value is -20. The setting must be between -20 and 20.
                  -node.session.xmit_thread_priority = -20
                  -
                  -
                  -#***************
                  -# iSCSI settings
                  -#***************
                  -
                  -# To enable R2T flow control (i.e., the initiator must wait for an R2T
                  -# command before sending any data), uncomment the following line:
                  -#
                  -#node.session.iscsi.InitialR2T = Yes
                  -#
                  -# To disable R2T flow control (i.e., the initiator has an implied
                  -# initial R2T of "FirstBurstLength" at offset 0), uncomment the following line:
                  -#
                  -# The defaults is No.
                  -node.session.iscsi.InitialR2T = No
                  -
                  -#
                  -# To disable immediate data (i.e., the initiator does not send
                  -# unsolicited data with the iSCSI command PDU), uncomment the following line:
                  -#
                  -#node.session.iscsi.ImmediateData = No
                  -#
                  -# To enable immediate data (i.e., the initiator sends unsolicited data
                  -# with the iSCSI command packet), uncomment the following line:
                  -#
                  -# The default is Yes
                  -node.session.iscsi.ImmediateData = Yes
                  -
                  -# To specify the maximum number of unsolicited data bytes the initiator
                  -# can send in an iSCSI PDU to a target, edit the following line.
                  -#
                  -# The value is the number of bytes in the range of 512 to (2^24-1) and
                  -# the default is 262144
                  -node.session.iscsi.FirstBurstLength = 262144
                  -
                  -# To specify the maximum SCSI payload that the initiator will negotiate
                  -# with the target for, edit the following line.
                  -#
                  -# The value is the number of bytes in the range of 512 to (2^24-1) and
                  -# the defauls it 16776192
                  -node.session.iscsi.MaxBurstLength = 16776192
                  -
                  -# To specify the maximum number of data bytes the initiator can receive
                  -# in an iSCSI PDU from a target, edit the following line.
                  -#
                  -# The value is the number of bytes in the range of 512 to (2^24-1) and
                  -# the default is 262144
                  -node.conn[0].iscsi.MaxRecvDataSegmentLength = 262144
                  -
                  -# To specify the maximum number of data bytes the initiator will send
                  -# in an iSCSI PDU to the target, edit the following line.
                  -#
                  -# The value is the number of bytes in the range of 512 to (2^24-1).
                  -# Zero is a special case. If set to zero, the initiator will use
                  -# the target's MaxRecvDataSegmentLength for the MaxXmitDataSegmentLength.
                  -# The default is 0.
                  -node.conn[0].iscsi.MaxXmitDataSegmentLength = 0
                  -
                  -# To specify the maximum number of data bytes the initiator can receive
                  -# in an iSCSI PDU from a target during a discovery session, edit the
                  -# following line.
                  -#
                  -# The value is the number of bytes in the range of 512 to (2^24-1) and
                  -# the default is 32768
                  -# 
                  -discovery.sendtargets.iscsi.MaxRecvDataSegmentLength = 32768
                  -
                  -# To allow the targets to control the setting of the digest checking,
                  -# with the initiator requesting a preference of enabling the checking, uncomment
                  -# the following lines (Data digests are not supported.):
                  -#node.conn[0].iscsi.HeaderDigest = CRC32C,None
                  -
                  -#
                  -# To allow the targets to control the setting of the digest checking,
                  -# with the initiator requesting a preference of disabling the checking,
                  -# uncomment the following line:
                  -#node.conn[0].iscsi.HeaderDigest = None,CRC32C
                  -#
                  -# To enable CRC32C digest checking for the header and/or data part of
                  -# iSCSI PDUs, uncomment the following line:
                  -#node.conn[0].iscsi.HeaderDigest = CRC32C
                  -#
                  -# To disable digest checking for the header and/or data part of
                  -# iSCSI PDUs, uncomment the following line:
                  -#node.conn[0].iscsi.HeaderDigest = None
                  -#
                  -# The default is to never use DataDigests or HeaderDigests.
                  -#
                  -node.conn[0].iscsi.HeaderDigest = None
                  -
                  -# For multipath configurations, you may want more than one session to be
                  -# created on each iface record.  If node.session.nr_sessions is greater
                  -# than 1, performing a 'login' for that node will ensure that the
                  -# appropriate number of sessions is created.
                  -node.session.nr_sessions = 1
                  -
                  -#************
                  -# Workarounds
                  -#************
                  -
                  -# Some targets like IET prefer after an initiator has sent a task
                  -# management function like an ABORT TASK or LOGICAL UNIT RESET, that
                  -# it does not respond to PDUs like R2Ts. To enable this behavior uncomment
                  -# the following line (The default behavior is Yes):
                  -node.session.iscsi.FastAbort = Yes
                  -
                  -# Some targets like Equalogic prefer that after an initiator has sent
                  -# a task management function like an ABORT TASK or LOGICAL UNIT RESET, that
                  -# it continue to respond to R2Ts. To enable this uncomment this line
                  -# node.session.iscsi.FastAbort = No
                  -
                  -# To prevent doing automatic scans that would add unwanted luns to the system
                  -# we can disable them and have sessions only do manually requested scans.
                  -# Automatic scans are performed on startup, on login, and on AEN/AER reception
                  -# on devices supporting it.  For HW drivers all sessions will use the value
                  -# defined in the configuration file.  This configuration option is independent
                  -# of scsi_mod scan parameter. (The default behavior is auto):
                  -node.session.scan = auto
                  +  discovery.sendtargets.iscsi.MaxRecvDataSegmentLength = 32768
                  +  node.conn[0].iscsi.MaxRecvDataSegmentLength = 262144
                  +  node.conn[0].timeo.login_timeout = 15
                  +  node.conn[0].timeo.logout_timeout = 15
                  +  node.conn[0].timeo.noop_out_interval = 5
                  +  node.conn[0].timeo.noop_out_timeout = 5
                  +  node.session.cmds_max = 128
                  +  node.session.err_timeo.abort_timeout = 15
                  +  node.session.err_timeo.lu_reset_timeout = 30
                  +  node.session.err_timeo.tgt_reset_timeout = 30
                  +  node.session.initial_login_retry_max = 8
                  +  node.session.iscsi.FastAbort = True
                  +  node.session.iscsi.FirstBurstLength = 262144
                  +  node.session.iscsi.ImmediateData = True
                  +  node.session.iscsi.MaxBurstLength = 16776192
                  +  node.session.nr_sessions = 1
                  +  node.session.queue_depth = 32
                  +  node.session.scan = auto
                  +  node.session.timeo.replacement_timeout = 120
                  +  node.session.xmit_thread_priority = -20
                  +  node.startup = manual
              mode:
                  0640
----------
          ID: iscsi_initiator_service
    Function: file.line
        Name: /etc/rc.conf
      Result: True
     Comment: onlyif condition is false
     Started: 19:15:25.086801
    Duration: 14.633 ms
     Changes:   
----------
          ID: iscsi_initiator_service
    Function: service.running
        Name: iscsi
      Result: True
     Comment: Service started
     Started: 19:15:25.191648
    Duration: 54.186 ms
     Changes:   
              ----------
              iscsi:
                  True

Summary for local
-------------
Succeeded: 15 (changed=4)
Failed:     3
-------------
Total states run:     18
```

**Comment by noelmcloughlin** [comment]
Works on FreeBSD without pillars:   [FreeBSD_without_Pillars.txt](https://github.com/saltstack-formulas/iscsi-formula/files/2189579/FreeBSD_without_Pillars.txt)

**Comment by noelmcloughlin** [comment]
PR works on OpenBSD with Pillars[FreeBSD_with_Pillars_WIP.txt](https://github.com/saltstack-formulas/iscsi-formula/files/2193695/FreeBSD_with_Pillars_WIP.txt) but I need to fix formatting in [map5.jinja](https://github.com/saltstack-formulas/iscsi-formula/pull/2/files#diff-9140c7c5aafc854783d21ac01d61850b)

**Comment by noelmcloughlin** [comment]
Fully verified on FreeBSD 11 with large pillars. Requires `ctld_env="-u"' entry in  `/etc/rc.conf ` first.

**Comment by noelmcloughlin** [comment]
This has been verified on Centos, Ubuntu, FreeBSD, Archlinux, and Suse.

**Comment by noelmcloughlin** [comment]
Here is the `saveconfig.json` generated from `pillar.example` data on Archlinux, Centos, Suse, Debian.  The `ctl.conf` on FreeBSD is similar too but UCL format (slight difference to JSON).  The ISCSI target,  initiator, and ISNS daemons are working on all Distro I tested.  

@javierbertoli @aboe76 Could you merge this PR now please?  Any issues and I'll fix in future PR.
```
{
        "fabric_modules": [
        {
            "discovery_enable_auth": "true",
            "discovery_mutual_password": "itsreallyme",
            "discovery_mutual_userid": "target",
            "discovery_password": "letmein",
            "discovery_userid": "initiator",
            "name": "iscsi"
        }
        ],

        "storage_objects": [
        {
            "attributes":
            {
                "block_size": 1024,
                "emulate_write_cache": 0,
                "max_sectors": 1024,
                "queue_depth": 128,
                "task_timeout": 0,
                "unmap_granularity": 0
            },

            "dev": "/dev/vg_storage/station4mp",
            "name": "mptarget4",
            "plugin": "block",
            "wwn": "6be30fb6-3bc9-43c4-a866-4d8633af5cf2"
        }
        ],

        "targets": [
        {
            "fabric": "iscsi",
            "tpgs": [
            {
                "attributes":
                {
                    "authentication": 1,
                    "cache_dynamic_acls": 0,
                    "default_cmdsn_depth": 16,
                    "demo_mode_write_protect": 1,
                    "generate_node_acls": 0,
                    "login_timeout": 15,
                    "netif_timeout": 2,
                    "prod_mode_write_protect": 0
                },

                "luns": [
                {
                    "index": 0,
                    "storage_object": "/backstores/block/mptarget4"
                }
                ],

                "node_acls": [
                {
                    "attributes":
                    {
                        "dataout_timeout": 3,
                        "dataout_timeout_retries": 5,
                        "default_erl": 0,
                        "nopin_response_timeout": 5,
                        "nopin_timeout": 5,
                        "random_datain_pdu_offsets": 0,
                        "random_datain_seq_offsets": 0,
                        "random_r2t_offsets": 0
                    },

                    "chap_mutual_password": "itsreallyme",
                    "chap_mutual_userid": "target",
                    "chap_password": "letmein",
                    "chap_userid": "station4",
                    "mapped_luns": [
                    {
                        "index": 0,
                        "tpg_lun": 0,
                        "write_protect": "false"
                    }
                    ],

                    "node_wwn": "iqn.1994-05.com.redhat:station4",
                    "tcq_depth": 16
                }
                ],

                "portals": [
                {
                    "ip_address": "10.100.0.199",
                    "port": 3260
                }
                ],

                "tag": 1
            }
            ],

            "wwn": "iqn.2003-01.org.linux-iscsi.storage:mptarget4"
        }
        ]
}
```

**Comment by aboe76** [comment]
@noelmcloughlin merged it.

**Comment by noelmcloughlin** [comment]
Thanks a million @aboe76

**Pull request merged**
