### PR TITLE
Add iscsi.remove

### PR DESCRIPTION
**Pull request by alxwr**
to remove once configured initiator(s) and target(s) and disable the service(s).

plus: minor bugfix in iscsi.target

### CODE REVIEW

**Comment by javierbertoli** [comment]
@alxwr, it LGTM, but mind you add some documentation in the `README.rst` file about this state?

**Comment by alxwr** [comment]
@javierbertoli good point! :-) I'll add documentation when my workload goes down a bit (which should be next week).

**Comment by alxwr** [comment]
@javierbertoli, I updated README.rst

**Comment by 0xf10e** [comment]
:+1:
I guess we're done here then.

**Comment by javierbertoli** [comment]
@alxwr did you read my last comment? The README says it removes the package, but the state does not do it. So I think we should either remove the package in the state file, or fix the README. We'd be done then. Do you agree?

**Comment by alxwr** [comment]
@javierbertoli My fingers were faster than my brain. The README.rst was incorrect. I fixed it. (`ctld` and `iscsid` are built into FreeBSD and can't be removed via `pkgng`.)
We're done here! Thanks!

**Comment by javierbertoli** [comment]
Merged, thanks @alxwr !

**Pull request merged**
